CREATE WAREHOUSE FROSTY_FRIDAY_COMPUTE
WAREHOUSE_SIZE = SMALL;

CREATE DATABASE FROSTY_FRIDAY;

CREATE SCHEMA WEEKLY_CHALLENGES;

CREATE STAGE WEEK1_S3
URL = 's3://frostyfridaychallenges/challenge_1/'
;

CREATE FILE FORMAT CSV_FORMAT
TYPE='CSV'
FIELD_DELIMITER=',';

SELECT  $1
FROM @WEEK1_S3
(FILE_FORMAT => 'CSV_FORMAT');

CREATE OR REPLACE TABLE WEEK1_CSV
(
COL1 TEXT
);

COPY INTO WEEK1_CSV
FROM 
    (SELECT  $1
FROM @WEEK1_S3
(FILE_FORMAT => 'CSV_FORMAT')
);

SELECT * FROM FROSTY_FRIDAY.WEEKLY_CHALLENGES.WEEK1_CSV